// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdeaKl6W_m0UvsIKNy6kMSzsjsaufVbtI',
    appId: '1:906749402598:web:9b1604b6034c047ae6ca27',
    messagingSenderId: '906749402598',
    projectId: 'expense-tracker-38524',
    authDomain: 'expense-tracker-38524.firebaseapp.com',
    storageBucket: 'expense-tracker-38524.firebasestorage.app',
    measurementId: 'G-D6MJ854BFT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4cf86oRLwYVUgRbl13uOjjSln8PSJ4bU',
    appId: '1:906749402598:android:afa079daa5aebe16e6ca27',
    messagingSenderId: '906749402598',
    projectId: 'expense-tracker-38524',
    storageBucket: 'expense-tracker-38524.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHzKAnAMW2BkO57f6p7ThypcZPC9k2fFQ',
    appId: '1:906749402598:ios:28b9cc618e802878e6ca27',
    messagingSenderId: '906749402598',
    projectId: 'expense-tracker-38524',
    storageBucket: 'expense-tracker-38524.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHzKAnAMW2BkO57f6p7ThypcZPC9k2fFQ',
    appId: '1:906749402598:ios:28b9cc618e802878e6ca27',
    messagingSenderId: '906749402598',
    projectId: 'expense-tracker-38524',
    storageBucket: 'expense-tracker-38524.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdeaKl6W_m0UvsIKNy6kMSzsjsaufVbtI',
    appId: '1:906749402598:web:06999d48a028b1a0e6ca27',
    messagingSenderId: '906749402598',
    projectId: 'expense-tracker-38524',
    authDomain: 'expense-tracker-38524.firebaseapp.com',
    storageBucket: 'expense-tracker-38524.firebasestorage.app',
    measurementId: 'G-TREWS85FEX',
  );
}
